### ISSUE TITLE
portfolio-polish

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/get-motivated-else-laugh#26]

**Comment by OSAdams** [comment]
## 💰 Motivation
The icons to display favorites aren't exactly direct in their functionality. Adding text should give the user clarification of what these icons do!

## 📐 Plan
Add text to icons, update page title, and update favorite star functionality.

## ✅ Task List
- [ ] Update web page title to Get Motivated else Laugh
- [ ] Create <spans> around the icons in the navigation bar
- [ ] Add text underneath icons to tell the user what they are used for
- [ ] Test functionality of the app
- [ ] Update DOM Manipulation functionality to the favorite icon to maintain the color change when clicked
